In [8]:
import numpy as np

# 假设 a 是你的数组
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a)
# 转置数组
a = a.T

# 打乱列
np.random.shuffle(a)

# 再次转置数组以恢复原始形状
a = a.T

print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[3 1 2]
 [6 4 5]
 [9 7 8]]
